### ISSUE TITLE
I can't use shortcuts.

### ISSUE THREAD

**Issue by emirhangunec** [a1usha/HideMyDock#2]
I'm using Macbook Pro 13" M1 16GB, and I can use the app with the menu bar, but I can't use it with the given shortcuts. Also, Hide Dock shortcut is assigned as the default copy shortcut. And the Show dock shortcut i is assigned as the default duplicate shortcut in Finder.

**Comment by a1usha** [comment]
Thank you for using my app, I'm glad it's useful!

Shortcuts you are talking about are not meant to be used globally or system wide, they only work when the app is in active state (expanded) in the menubar. From this point of view they are kinda useless in my opinion.

System wide shortcuts are not implemented yet.
